### ISSUE TITLE
Exception: Training dataset files not found!

### ISSUE THREAD

**Issue by sankexin** [chrisociepa/allamo#17]
https://github.com/karpathy/nanoGPT/blob/master/data/shakespeare/prepare.py

../data/allamo_1B_dataset/

```
input.txt  
train.bin
val.bin
```

The idea for this project is great, thank you. Is it correct to use the data in this way? I hope to further improve the entire project by providing pre trained open source Llama3. I am also considering contributing the Llama3 open source code trained from scratch to the open source community.

**Comment by chrisociepa** [comment]
Yes, that's correct. There's also an alternative supported dataset format where, instead of a numpy array, you use a tensor. In this case, you concatenate all tensors for the documents just as you would with numpy, but in the end, you save the resulting tensor with `torch.save(final_tensor, "train.pt")`.

**Comment by sankexin** [comment]
> Yes, that's correct. There's also an alternative supported dataset format where, instead of a numpy array, you use a tensor. In this case, you concatenate all tensors for the documents just as you would with numpy, but in the end, you save the resulting tensor with `torch.save(final_tensor, "train.pt")`.

thanks for your reply, when use the above data('https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt') ,have you meet this error:

'''
<frozen importlib._bootstrap_external>:843: _call_with_frames_removed: block: [966,0,0], thread: [91,0,0] Assertion `index out of bounds: 0 <= tmp3 < 8000` failed.
<frozen importlib._bootstrap_external>:843: _call_with_frames_removed: block: [966,0,0], thread: [92,0,0] Assertion `index out of bounds: 0 <= tmp3 < 8000` failed.
<frozen importlib._bootstrap_external>:843: _call_with_frames_removed: block: [966,0,0], thread: [93,0,0] Assertion `index out of bounds: 0 <= tmp3 < 8000` failed.
<frozen importlib._bootstrap_external>:843: _call_with_frames_removed: block: [966,0,0], thread: [94,0,0] Assertion `index out of bounds: 0 <= tmp3 < 8000` failed.
<frozen importlib._bootstrap_external>:843: _call_with_frames_removed: block: [966,0,0], thread: [95,0,0] Assertion `index out of bounds: 0 <= tmp3 < 8000` failed.
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    trainer.train()
  File "/home/allamo/allamo/trainer/base.py", line 261, in train
    self.evaluate()
  File "/home/allamo/allamo/trainer/base.py", line 183, in evaluate
    losses, accuraces = self.estimate_loss()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/allamo/allamo/trainer/base.py", line 166, in estimate_loss
    logits, loss, _ = self.model(**batch)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/allamo/allamo/model/model.py", line 406, in forward
    def forward(self,
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/external_utils.py", line 36, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 917, in forward
    return compiled_fn(full_args)
  File "/opt/conda/lib/python3.8/site-packages/torch/_functorch/_aot_autograd/utils.py", line 89, in g
    return f(*args)
  File "/opt/conda/lib/python3.8/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 106, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
  File "/opt/conda/lib/python3.8/site-packages/torch/_functorch/_aot_autograd/utils.py", line 113, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 152, in rng_functionalization_wrapper
    return compiled_fw(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/_inductor/codecache.py", line 906, in __call__
    return self.get_current_callable()(inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 784, in run
    return model(new_inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_inductor/codecache.py", line 934, in _run_from_cache
    return compiled_graph.compiled_artifact(inputs)
  File "/tmp/torchinductor_root/3g/c3guutbjlhkl66radd4espizloapprtlvmz3d344zjdqgl76qxhk.py", line 1223, in call
    triton_red_fused_add_embedding_mean_mul_pow_rsqrt_0.run(arg185_1, arg41_1, arg0_1, buf1, 2048, 2048, grid=grid(2048), stream=stream0)
  File "/opt/conda/lib/python3.8/site-packages/torch/_inductor/triton_heuristics.py", line 635, in run
    self.autotune_to_one_config(*args, grid=grid, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_inductor/triton_heuristics.py", line 531, in autotune_to_one_config
    timings = self.benchmark_all_configs(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_inductor/triton_heuristics.py", line 507, in benchmark_all_configs
    timings = {
  File "/opt/conda/lib/python3.8/site-packages/torch/_inductor/triton_heuristics.py", line 508, in <dictcomp>
    launcher: self.bench(launcher, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_inductor/triton_heuristics.py", line 479, in bench
    return do_bench(kernel_call, rep=40, fast_flush=True)
  File "/opt/conda/lib/python3.8/site-packages/torch/_inductor/utils.py", line 170, in do_bench
    return triton_do_bench(*args, **kwargs)[0]
  File "/opt/conda/lib/python3.8/site-packages/triton/testing.py", line 103, in do_bench
    torch.cuda.synchronize()
  File "/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py", line 792, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
'''

I have printed the batch data, But the problem hasn't been identified yet, like this:

'''
batch: {'input_ids': tensor([[    11,    416,    262,  ..., -17174,      0,    198]],
       device='cuda:0'), 'target_ids': tensor([[   416,    262, -28931,  ...,      0,    198,     40]],
       device='cuda:0'), 'target_weights': None, 'attn_mask': None, 'input_pos': None}
'''

**Comment by chrisociepa** [comment]
I don’t recall seeing this error before. Maybe the shape of the data in the batch is incorrect? Check the shape of `input_ids` and `target_ids`. Both should have the same length equal to `block_size`.
You could also try running it with compile=False to make it easier to pinpoint the issue.

**Comment by sankexin** [comment]
> I don’t recall seeing this error before. Maybe the shape of the data in the batch is incorrect? Check the shape of `input_ids` and `target_ids`. Both should have the same length equal to `block_size`. You could also try running it with compile=False to make it easier to pinpoint the issue.

good tips, I modified this vocab_size,  find from vocab_size  of nanoGP , and done!

train_configs/train_1B.json
'''
"vocab_size": 50304
'''
